"""Recipe retrieval over a curated local recipe catalog."""

from __future__ import annotations

import re

from app.models.recipe import Recipe
from app.models.user_state import UserState


class RetrievalService:
    def __init__(self) -> None:
        self._catalog = self._build_catalog()

    def retrieve(self, user_state: UserState, limit: int = 8) -> list[Recipe]:
        candidates = [recipe for recipe in self._catalog if self._matches_diet(recipe, user_state.diet)]
        candidates = [recipe for recipe in candidates if self._matches_intent(recipe, user_state)]
        if not candidates:
            candidates = list(self._catalog)

        ranked_candidates = sorted(
            candidates,
            key=lambda recipe: self._quick_relevance(recipe, user_state),
            reverse=True,
        )
        return ranked_candidates[:limit]

    def _matches_intent(self, recipe: Recipe, user_state: UserState) -> bool:
        desired = self._desired_difficulty_values(user_state.challenge_level)
        if recipe.difficulty_level not in desired and user_state.goal in {"learn", "gourmet"}:
            if recipe.difficulty_level < min(desired):
                return False

        if user_state.goal == "convenience" and recipe.difficulty_level >= 4:
            return False

        if user_state.time_available:
            recipe_minutes = recipe.total_minutes or recipe.prep_minutes + recipe.cook_minutes
            if user_state.goal == "convenience" and recipe_minutes > user_state.time_available * 1.5:
                return False
            if user_state.goal in {"learn", "gourmet"} and recipe_minutes < max(45, user_state.time_available // 2):
                return False

        if user_state.goal == "comfort" and recipe.comfort_score < 5:
            return False

        available = self._tokens(user_state.available_ingredients or user_state.ingredients)
        required = self._tokens(recipe.ingredients_needed)
        overlap = len(available & required)
        if available and user_state.goal != "learn" and overlap == 0 and recipe.difficulty_level >= 4:
            return False

        return True

    def _matches_diet(self, recipe: Recipe, diet: str) -> bool:
        normalized_diet = diet.strip().lower()
        if not normalized_diet:
            return True
        if normalized_diet in recipe.diet_tags:
            return True
        if normalized_diet == "vegetarian":
            return "vegetarian" in recipe.diet_tags or "vegan" in recipe.diet_tags
        if normalized_diet == "vegan":
            return "vegan" in recipe.diet_tags
        if normalized_diet == "gluten-free":
            return "gluten-free" in recipe.diet_tags
        if normalized_diet == "keto":
            return "keto" in recipe.diet_tags
        return True

    def _quick_relevance(self, recipe: Recipe, user_state: UserState) -> float:
        score = 0.0
        emotion_hits = {user_state.primary_emotion, user_state.secondary_emotion}
        if any(emotion and emotion in recipe.emotion_tags for emotion in emotion_hits):
            score += 3.0
        if user_state.comfort_food and recipe.comfort_score >= 7:
            score += 2.0
        if user_state.meal_type and recipe.meal_type == user_state.meal_type:
            score += 1.2

        if user_state.goal == "learn" and recipe.learning_value >= 7:
            score += 2.2
        if user_state.goal == "gourmet" and recipe.difficulty_level >= 4:
            score += 2.0
        if user_state.goal == "convenience" and recipe.difficulty_level <= 2:
            score += 1.8

        available_tokens = self._tokens(user_state.ingredients)
        recipe_tokens = self._tokens(recipe.ingredients_needed)
        overlap = len(available_tokens & recipe_tokens)
        score += min(2.0, overlap * 0.5)

        if user_state.time_available and recipe.total_minutes:
            time_gap = abs(recipe.total_minutes - user_state.time_available)
            score += max(0.0, 1.5 - (time_gap / max(user_state.time_available, 10)))

        if user_state.preferred_tastes:
            taste_overlap = len({taste.lower() for taste in user_state.preferred_tastes} & {taste.lower() for taste in recipe.taste_profile})
            score += min(1.5, taste_overlap * 0.5)

        if user_state.spice_level == "hot" and "spicy" in recipe.taste_profile:
            score += 0.8
        if user_state.spice_level == "mild" and "mild" in recipe.taste_profile:
            score += 0.5

        return score

    @staticmethod
    def _desired_difficulty_values(challenge_level: str) -> set[int]:
        mapping = {
            "very_easy": {1},
            "easy": {1, 2},
            "medium": {2, 3},
            "hard": {4},
            "expert": {5},
        }
        return mapping.get(challenge_level.lower(), {2, 3})

    def _build_catalog(self) -> list[Recipe]:
        catalog_data = [
            {
                "name": "Lemon Herb Chicken Soup",
                "cuisine": "Comfort",
                "difficulty": "Easy",
                "prep_time": "10 minutes",
                "cook_time": "20 minutes",
                "servings": 2,
                "comfort_score": 9,
                "emotion_tags": ["sad", "heartbroken", "lonely", "tired", "sick"],
                "taste_profile": ["warm", "savory", "bright", "comforting"],
                "texture": "brothy",
                "temperature": "warm",
                "occasion": "reset meal",
                "energy_required": "low",
                "meal_type": "soup",
                "diet_tags": ["gluten-free"],
                "budget": "low",
                "prep_minutes": 10,
                "cook_minutes": 20,
                "total_minutes": 30,
                "nutrition_score": 8.5,
                "ingredients_needed": [
                    "boneless chicken breast (250 g)",
                    "garlic cloves (2, minced)",
                    "lemon (1, juice and zest)",
                    "carrot (1, diced)",
                    "celery stalks (2, sliced)",
                    "chicken broth (3 cups)",
                    "olive oil (1 tbsp)",
                    "salt and black pepper (to taste)"
                ],
                "missing_ingredients": ["fresh parsley (optional, chopped)", "red pepper flakes (optional)"] ,
                "instructions": [
                    "Step 1: Place a medium soup pot over medium heat and add the olive oil. Once it shimmers, add the minced garlic and diced carrot, then stir for 2-3 minutes until the garlic smells fragrant and the carrot starts to soften.",
                    "Step 2: Add the chicken pieces and stir them for about 1 minute so the outside turns opaque and starts to pick up the garlic flavor.",
                    "Step 3: Pour in the broth, then add the celery, lemon juice, lemon zest, salt, and black pepper. Stir well so the liquid covers the ingredients evenly.",
                    "Step 4: Bring the pot to a gentle simmer, lower the heat, and cook uncovered for 15-18 minutes. Stir once or twice so nothing sticks to the bottom of the pot.",
                    "Step 5: Taste the broth, adjust seasoning if needed, then turn off the heat. Let the soup rest for 2 minutes so the flavor settles, and finish with parsley or red pepper flakes if you want a brighter edge.",
                ],
                "nutrition_per_serving": {"calories": 320, "protein": "28g", "carbs": "18g", "fat": "12g"},
                "tips": "Finish with extra lemon for a brighter, more comforting bowl.",
            },
            {
                "name": "Creamy Garlic Mushroom Pasta",
                "cuisine": "Italian-inspired",
                "difficulty": "Easy",
                "prep_time": "12 minutes",
                "cook_time": "18 minutes",
                "servings": 2,
                "comfort_score": 10,
                "emotion_tags": ["sad", "heartbroken", "lonely", "nostalgic", "cozy"],
                "taste_profile": ["rich", "savory", "comforting", "warm"],
                "texture": "creamy",
                "temperature": "warm",
                "occasion": "comfort dinner",
                "energy_required": "low",
                "meal_type": "main",
                "diet_tags": ["vegetarian"],
                "budget": "medium",
                "prep_minutes": 12,
                "cook_minutes": 18,
                "total_minutes": 30,
                "nutrition_score": 6.8,
                "ingredients_needed": ["pasta", "garlic", "mushrooms", "cream", "parmesan"],
                "missing_ingredients": ["spinach"],
                "instructions": [
                    "Step 1: Bring a pot of salted water to a boil and cook the pasta until just tender. Reserve a small cup of pasta water before draining.",
                    "Step 2: Heat a skillet over medium heat and sauté the garlic and mushrooms until the mushrooms release their liquid and start to brown.",
                    "Step 3: Add the cream and a splash of pasta water, then stir until the sauce looks smooth and lightly thickened.",
                    "Step 4: Toss the pasta into the sauce so every piece is coated evenly. If the sauce gets too thick, loosen it with a little more pasta water.",
                    "Step 5: Finish with parmesan, taste for salt, and serve right away while the sauce is still creamy.",
                ],
                "nutrition_per_serving": {"calories": 540, "protein": "18g", "carbs": "62g", "fat": "24g"},
                "tips": "Use reserved pasta water to keep the sauce silky without extra effort.",
            },
            {
                "name": "Chocolate Banana Mug Cake",
                "cuisine": "Dessert",
                "difficulty": "Very Easy",
                "prep_time": "5 minutes",
                "cook_time": "2 minutes",
                "servings": 1,
                "comfort_score": 10,
                "emotion_tags": ["heartbroken", "sad", "lonely", "celebratory"],
                "taste_profile": ["sweet", "rich", "warm"],
                "texture": "soft",
                "temperature": "warm",
                "occasion": "solo comfort treat",
                "energy_required": "minimal",
                "meal_type": "dessert",
                "diet_tags": ["vegetarian"],
                "budget": "low",
                "prep_minutes": 5,
                "cook_minutes": 2,
                "total_minutes": 7,
                "nutrition_score": 5.0,
                "ingredients_needed": ["banana", "cocoa powder", "flour", "milk", "chocolate"],
                "missing_ingredients": ["baking powder"],
                "instructions": [
                    "Step 1: Mash the banana in a mug or small bowl until mostly smooth, then add the cocoa, flour, milk, and baking powder.",
                    "Step 2: Stir everything together until the batter is smooth and there are no dry pockets at the bottom.",
                    "Step 3: Fold in the chocolate chips if you want extra pockets of melted chocolate.",
                    "Step 4: Microwave for 70-90 seconds, checking near the end so the cake rises without drying out.",
                    "Step 5: Let it rest for a minute before eating so the center sets slightly and stays soft instead of runny.",
                ],
                "nutrition_per_serving": {"calories": 290, "protein": "6g", "carbs": "44g", "fat": "10g"},
                "tips": "Top with a few nuts or a spoon of yogurt if you want extra texture.",
            },
            {
                "name": "Ginger Soy Tofu Rice Bowl",
                "cuisine": "Asian-inspired",
                "difficulty": "Easy",
                "prep_time": "10 minutes",
                "cook_time": "15 minutes",
                "servings": 2,
                "comfort_score": 6,
                "emotion_tags": ["focused", "energetic", "guilty"],
                "taste_profile": ["savory", "fresh", "balanced", "light"],
                "texture": "tender",
                "temperature": "warm",
                "occasion": "weekday reset",
                "energy_required": "low",
                "meal_type": "main",
                "diet_tags": ["vegan", "vegetarian", "gluten-free"],
                "budget": "low",
                "prep_minutes": 10,
                "cook_minutes": 15,
                "total_minutes": 25,
                "nutrition_score": 8.8,
                "ingredients_needed": ["tofu", "rice", "soy sauce", "ginger", "scallions", "sesame oil"],
                "missing_ingredients": ["broccoli", "sesame seeds"],
                "instructions": [
                    "Step 1: Press or pat the tofu dry, then cut it into cubes so it browns more evenly in the pan.",
                    "Step 2: Heat a little oil in a skillet and cook the tofu until the edges are golden and crisp.",
                    "Step 3: Add the ginger and soy sauce, then stir until the tofu is coated and the sauce starts to glaze the pan.",
                    "Step 4: Build the bowl with warm rice and scallions, then add any greens you have on hand.",
                    "Step 5: Finish with sesame oil for a bright final layer of flavor and serve while warm.",
                ],
                "nutrition_per_serving": {"calories": 430, "protein": "22g", "carbs": "48g", "fat": "14g"},
                "tips": "Add steamed broccoli or edamame if you want more volume without much extra effort.",
            },
            {
                "name": "Citrus Salmon Quinoa Bowl",
                "cuisine": "Modern healthy",
                "difficulty": "Easy",
                "prep_time": "12 minutes",
                "cook_time": "18 minutes",
                "servings": 2,
                "comfort_score": 5,
                "emotion_tags": ["focused", "energetic", "stressed", "guilty"],
                "taste_profile": ["fresh", "bright", "light", "savory"],
                "texture": "flaky",
                "temperature": "warm",
                "occasion": "balanced dinner",
                "energy_required": "low",
                "meal_type": "main",
                "diet_tags": ["gluten-free"],
                "budget": "high",
                "prep_minutes": 12,
                "cook_minutes": 18,
                "total_minutes": 30,
                "nutrition_score": 9.0,
                "ingredients_needed": ["salmon", "quinoa", "lemon", "greens", "olive oil"],
                "missing_ingredients": ["avocado", "cucumber"],
                "instructions": [
                    "Step 1: Heat the oven and place the salmon on a lined tray. Brush it with olive oil and season it with salt, pepper, and lemon.",
                    "Step 2: Roast the salmon until it flakes easily with a fork and the top looks lightly set.",
                    "Step 3: While the salmon cooks, build the quinoa base with any greens or chopped vegetables you have.",
                    "Step 4: Whisk a simple citrus dressing from lemon juice and olive oil, then drizzle it over the bowl.",
                    "Step 5: Place the salmon on top, taste once more for seasoning, and serve warm.",
                ],
                "nutrition_per_serving": {"calories": 510, "protein": "34g", "carbs": "34g", "fat": "24g"},
                "tips": "Keep the dressing simple so the bowl stays fast and clean-tasting.",
            },
            {
                "name": "Smoky Chickpea Tacos with Lime Slaw",
                "cuisine": "Mexican-inspired",
                "difficulty": "Easy",
                "prep_time": "12 minutes",
                "cook_time": "15 minutes",
                "servings": 2,
                "comfort_score": 7,
                "emotion_tags": ["bored", "adventurous", "angry"],
                "taste_profile": ["bold", "spicy", "tangy", "crunchy"],
                "texture": "crisp",
                "temperature": "warm",
                "occasion": "fun weeknight",
                "energy_required": "low",
                "meal_type": "main",
                "diet_tags": ["vegan", "vegetarian"],
                "budget": "low",
                "prep_minutes": 12,
                "cook_minutes": 15,
                "total_minutes": 27,
                "nutrition_score": 7.6,
                "ingredients_needed": ["chickpeas", "tortillas", "lime", "cabbage", "smoked paprika"],
                "missing_ingredients": ["yogurt", "cilantro"],
                "instructions": [
                    "Step 1: Warm a skillet over medium heat and season the chickpeas with smoked paprika and salt so they have a strong base flavor.",
                    "Step 2: Cook the chickpeas for a few minutes until they are lightly crisp on the outside and hot all the way through.",
                    "Step 3: Mix the cabbage with lime juice and a little salt to make a quick slaw that stays crunchy.",
                    "Step 4: Warm the tortillas so they fold easily, then fill each one with the chickpeas and slaw.",
                    "Step 5: Add the sauce or yogurt if using, then serve right away so the tortillas stay soft and the slaw stays crisp.",
                ],
                "nutrition_per_serving": {"calories": 390, "protein": "15g", "carbs": "46g", "fat": "16g"},
                "tips": "A pinch of smoked paprika makes these feel more exciting without adding much work.",
            },
            {
                "name": "Cozy Tomato Basil Orzo",
                "cuisine": "Italian-inspired",
                "difficulty": "Easy",
                "prep_time": "8 minutes",
                "cook_time": "20 minutes",
                "servings": 2,
                "comfort_score": 9,
                "emotion_tags": ["nostalgic", "cozy", "sad", "lonely"],
                "taste_profile": ["warm", "savory", "comforting", "soft"],
                "texture": "creamy",
                "temperature": "warm",
                "occasion": "comfort lunch",
                "energy_required": "low",
                "meal_type": "main",
                "diet_tags": ["vegetarian"],
                "budget": "low",
                "prep_minutes": 8,
                "cook_minutes": 20,
                "total_minutes": 28,
                "nutrition_score": 7.2,
                "ingredients_needed": [
                    "orzo (1 cup)",
                    "tomatoes (2 medium, diced)",
                    "fresh basil (1/4 cup, chopped)",
                    "garlic cloves (2, minced)",
                    "vegetable broth (2 1/2 cups)",
                    "olive oil (1 tbsp)",
                    "salt and pepper (to taste)"
                ],
                "missing_ingredients": ["parmesan (2 tbsp, optional)", "cream (2 tbsp, optional)"] ,
                "instructions": [
                    "Step 1: Warm the olive oil in a wide saucepan over medium heat, then add the garlic and toast the orzo for 1-2 minutes. Stir often so the grains get lightly coated and start to smell nutty without browning too fast.",
                    "Step 2: Stir in the diced tomatoes and broth, scraping the bottom of the pan so nothing sticks. Bring it to a steady simmer and cook uncovered for 8 minutes.",
                    "Step 3: Keep stirring every few minutes as the orzo softens and the liquid reduces. If the pan looks dry too soon, add a splash of water or broth.",
                    "Step 4: Once the grains are tender and the mixture looks creamy, fold in the basil and season with salt and pepper. Taste the orzo and adjust the tomato or salt balance if needed.",
                    "Step 5: If you want a richer finish, add parmesan or a small spoon of cream at the end and let it melt through for a minute before serving.",
                ],
                "nutrition_per_serving": {"calories": 410, "protein": "12g", "carbs": "58g", "fat": "14g"},
                "tips": "Add a splash of cream or extra olive oil only if you want it richer.",
            },
            {
                "name": "Avocado Egg Toast with Chili Flakes",
                "cuisine": "Quick brunch",
                "difficulty": "Very Easy",
                "prep_time": "7 minutes",
                "cook_time": "5 minutes",
                "servings": 1,
                "comfort_score": 6,
                "emotion_tags": ["focused", "energetic", "lazy", "tired"],
                "taste_profile": ["fresh", "savory", "light"],
                "texture": "crisp",
                "temperature": "warm",
                "occasion": "fast meal",
                "energy_required": "minimal",
                "meal_type": "breakfast",
                "diet_tags": ["vegetarian"],
                "budget": "low",
                "prep_minutes": 7,
                "cook_minutes": 5,
                "total_minutes": 12,
                "nutrition_score": 8.0,
                "ingredients_needed": [
                    "bread slices (2, toasted)",
                    "avocado (1 ripe, mashed)",
                    "egg (1, cooked to preference)",
                    "lemon juice (1 tsp)",
                    "chili flakes (1/4 tsp)",
                    "salt and pepper (to taste)",
                    "olive oil or butter (1 tsp, optional)"
                ],
                "missing_ingredients": ["spinach (1 cup, optional)"] ,
                "instructions": [
                    "Step 1: Toast the bread until the outside is crisp but the center still has a little softness. This helps the avocado stay balanced and keeps the toast from getting soggy.",
                    "Step 2: Mash the avocado in a small bowl with lemon juice, salt, and pepper. Keep it slightly chunky so the topping has better texture.",
                    "Step 3: Cook the egg the way you like it, such as soft scrambled, fried, or poached. A runny yolk gives the toast a richer finish, while a firm yolk keeps it neat.",
                    "Step 4: Spread the avocado evenly over the toast, then place the egg on top. Add a small pinch of chili flakes for gentle heat.",
                    "Step 5: Finish with a light drizzle of olive oil or a tiny pinch more salt if needed, then serve right away while the toast is still crisp.",
                ],
                "nutrition_per_serving": {"calories": 310, "protein": "12g", "carbs": "24g", "fat": "18g"},
                "tips": "A squeeze of lemon keeps it bright and prevents the avocado from feeling heavy.",
            },
            {
                "name": "Warm Lentil Coconut Curry",
                "cuisine": "South Asian-inspired",
                "difficulty": "Easy",
                "prep_time": "12 minutes",
                "cook_time": "22 minutes",
                "servings": 3,
                "comfort_score": 8,
                "emotion_tags": ["stressed", "cozy", "guilty", "sick"],
                "taste_profile": ["warm", "balanced", "comforting", "savory"],
                "texture": "thick",
                "temperature": "warm",
                "occasion": "reset meal",
                "energy_required": "low",
                "meal_type": "main",
                "diet_tags": ["vegan", "vegetarian", "gluten-free"],
                "budget": "low",
                "prep_minutes": 12,
                "cook_minutes": 22,
                "total_minutes": 34,
                "nutrition_score": 8.4,
                "ingredients_needed": ["lentils", "coconut milk", "onion", "garlic", "curry powder"],
                "missing_ingredients": ["spinach", "rice"],
                "instructions": [
                    "Step 1: Heat a pot over medium heat and cook the onion with a little oil until it turns soft and translucent.",
                    "Step 2: Add the garlic and curry powder, then stir for 30 seconds so the spices bloom and smell stronger.",
                    "Step 3: Add the lentils and coconut milk, then pour in enough water to cover everything by about 1 inch.",
                    "Step 4: Bring the pot to a gentle simmer and cook until the lentils are tender and the curry starts to thicken. Stir every few minutes so it does not stick.",
                    "Step 5: Taste and adjust salt or lime at the end, then serve with rice or greens if you have them.",
                ],
                "nutrition_per_serving": {"calories": 440, "protein": "18g", "carbs": "46g", "fat": "18g"},
                "tips": "A squeeze of lime at the end keeps the curry feeling lively instead of heavy.",
            },
            {
                "name": "Berry Yogurt Crunch Parfait",
                "cuisine": "Breakfast / Snack",
                "difficulty": "Very Easy",
                "prep_time": "5 minutes",
                "cook_time": "0 minutes",
                "servings": 1,
                "comfort_score": 5,
                "emotion_tags": ["focused", "energetic", "anxious", "guilty"],
                "taste_profile": ["fresh", "sweet", "light"],
                "texture": "crunchy",
                "temperature": "cold",
                "occasion": "light snack",
                "energy_required": "minimal",
                "meal_type": "snack",
                "diet_tags": ["vegetarian", "gluten-free"],
                "budget": "low",
                "prep_minutes": 5,
                "cook_minutes": 0,
                "total_minutes": 5,
                "nutrition_score": 8.7,
                "ingredients_needed": ["yogurt", "berries", "oats", "honey"],
                "missing_ingredients": ["nuts", "chia seeds"],
                "instructions": [
                    "Step 1: Choose a bowl or tall glass and add a spoonful of yogurt to the bottom so the layers stay neat.",
                    "Step 2: Add a layer of berries, then scatter oats or nuts on top for crunch.",
                    "Step 3: Repeat the layers if you have enough ingredients, keeping the yogurt as the base and the berries in the middle.",
                    "Step 4: Drizzle honey over the top so the sweetness spreads through the bowl instead of pooling in one spot.",
                    "Step 5: Serve immediately for the best texture, especially if you want the oats to stay crisp.",
                ],
                "nutrition_per_serving": {"calories": 260, "protein": "15g", "carbs": "28g", "fat": "8g"},
                "tips": "Use frozen berries if that is what you have; they thaw quickly in the yogurt.",
            },
            {
                "name": "Sesame Noodle Bowl with Greens",
                "cuisine": "Asian-inspired",
                "difficulty": "Easy",
                "prep_time": "10 minutes",
                "cook_time": "12 minutes",
                "servings": 2,
                "comfort_score": 7,
                "emotion_tags": ["bored", "adventurous", "energetic"],
                "taste_profile": ["savory", "tangy", "light", "crunchy"],
                "texture": "tossed",
                "temperature": "warm",
                "occasion": "quick dinner",
                "energy_required": "low",
                "meal_type": "main",
                "diet_tags": ["vegetarian"],
                "budget": "low",
                "prep_minutes": 10,
                "cook_minutes": 12,
                "total_minutes": 22,
                "nutrition_score": 7.8,
                "ingredients_needed": ["noodles", "sesame oil", "soy sauce", "greens", "carrot"],
                "missing_ingredients": ["peanuts", "lime"],
                "instructions": [
                    "Step 1: Cook the noodles in salted water until just tender, then drain and rinse briefly so they do not stick together.",
                    "Step 2: Whisk the sesame oil, soy sauce, and a little water together to make a quick sauce.",
                    "Step 3: Toss the warm noodles with the sauce and add the greens while they are still hot enough to soften slightly.",
                    "Step 4: Add the carrot and any crunchy toppings so the bowl gets some contrast in texture.",
                    "Step 5: Taste and adjust the seasoning with a little more soy sauce or lime before serving.",
                ],
                "nutrition_per_serving": {"calories": 390, "protein": "13g", "carbs": "52g", "fat": "13g"},
                "tips": "Add chili oil only if you want more punch; the bowl already has good flavor balance.",
            },
            {
                "name": "Celebration Berry Pancakes",
                "cuisine": "Brunch / Dessert",
                "difficulty": "Easy",
                "prep_time": "10 minutes",
                "cook_time": "12 minutes",
                "servings": 2,
                "comfort_score": 8,
                "emotion_tags": ["happy", "celebratory", "romantic"],
                "taste_profile": ["sweet", "bright", "festive"],
                "texture": "fluffy",
                "temperature": "warm",
                "occasion": "celebration",
                "energy_required": "medium",
                "meal_type": "dessert",
                "diet_tags": ["vegetarian"],
                "budget": "low",
                "prep_minutes": 10,
                "cook_minutes": 12,
                "total_minutes": 22,
                "nutrition_score": 6.5,
                "ingredients_needed": ["flour", "milk", "egg", "berries", "syrup"],
                "missing_ingredients": ["vanilla", "baking powder"],
                "instructions": [
                    "Step 1: Whisk the flour, milk, egg, and baking powder together until the batter is smooth but still a little thick.",
                    "Step 2: Heat a nonstick pan over medium heat and lightly grease it so the pancakes release easily.",
                    "Step 3: Pour small circles of batter into the pan and cook until bubbles form on the surface and the edges look set.",
                    "Step 4: Flip the pancakes and cook the second side until golden and cooked through.",
                    "Step 5: Stack with berries on top and add a light drizzle of syrup before serving while warm.",
                ],
                "nutrition_per_serving": {"calories": 420, "protein": "11g", "carbs": "58g", "fat": "16g"},
                "tips": "A little lemon zest makes the berries taste brighter with almost no extra work.",
            },
            {
                "name": "Ramen-Style Broth Bowl with Soft Eggs",
                "cuisine": "Japanese-inspired",
                "difficulty": "Easy",
                "prep_time": "10 minutes",
                "cook_time": "15 minutes",
                "servings": 2,
                "comfort_score": 9,
                "emotion_tags": ["lonely", "cozy", "tired", "heartbroken", "sick"],
                "taste_profile": ["warm", "savory", "comforting", "rich"],
                "texture": "slurpy",
                "temperature": "warm",
                "occasion": "comfort bowl",
                "energy_required": "low",
                "meal_type": "soup",
                "diet_tags": ["vegetarian"],
                "budget": "medium",
                "prep_minutes": 10,
                "cook_minutes": 15,
                "total_minutes": 25,
                "nutrition_score": 7.4,
                "ingredients_needed": ["noodles", "broth", "egg", "scallions", "soy sauce"],
                "missing_ingredients": ["mushrooms", "spinach"],
                "instructions": [
                    "Step 1: Bring the broth to a gentle simmer with soy sauce and any aromatics like garlic, ginger, or onion.",
                    "Step 2: Cook the noodles separately so they stay springy, then drain them well.",
                    "Step 3: Soft-boil the eggs until the whites are set and the yolks are still a little jammy.",
                    "Step 4: Place the noodles in bowls, pour the hot broth over them, and add the eggs on top.",
                    "Step 5: Finish with scallions and serve right away while the broth is still steaming hot.",
                ],
                "nutrition_per_serving": {"calories": 460, "protein": "19g", "carbs": "54g", "fat": "16g"},
                "tips": "Keep the broth simple and hot; that is what makes this feel restorative.",
            },
            {
                "name": "Turkey-Free Protein Wrap with Herby Sauce",
                "cuisine": "Quick lunch",
                "difficulty": "Easy",
                "prep_time": "8 minutes",
                "cook_time": "7 minutes",
                "servings": 1,
                "comfort_score": 5,
                "emotion_tags": ["focused", "energetic", "guilty", "lazy"],
                "taste_profile": ["fresh", "light", "savory"],
                "texture": "crisp",
                "temperature": "cool",
                "occasion": "desk lunch",
                "energy_required": "minimal",
                "meal_type": "lunch",
                "diet_tags": ["vegetarian"],
                "budget": "low",
                "prep_minutes": 8,
                "cook_minutes": 7,
                "total_minutes": 15,
                "nutrition_score": 8.2,
                "ingredients_needed": ["wrap", "beans", "greens", "yogurt", "herbs"],
                "missing_ingredients": ["cucumber", "tomato"],
                "instructions": [
                    "Step 1: Stir the yogurt and herbs together to make the quick sauce, then season it with a little salt and pepper.",
                    "Step 2: Warm the wrap for a few seconds so it bends easily and does not crack when rolled.",
                    "Step 3: Spread the sauce across the wrap, leaving a small border around the edges so it does not spill out.",
                    "Step 4: Add the beans, greens, and crunchy vegetables in a tight line through the center.",
                    "Step 5: Roll the wrap firmly, cut it in half if you want, and eat while the filling is still fresh.",
                ],
                "nutrition_per_serving": {"calories": 340, "protein": "17g", "carbs": "36g", "fat": "12g"},
                "tips": "A spoonful of beans gives this enough substance without adding much work.",
            },
            {
                "name": "Beef Wellington",
                "cuisine": "French-inspired",
                "difficulty": "Expert",
                "difficulty_level": 5,
                "prep_time": "45 minutes",
                "cook_time": "35 minutes",
                "servings": 4,
                "comfort_score": 7,
                "learning_value": 10,
                "techniques": ["searing", "duxelles", "pastry wrapping", "resting"],
                "estimated_cleanup": "high",
                "skill_tags": ["precision", "timing", "pastry"],
                "emotion_tags": ["celebratory", "curious", "focused"],
                "taste_profile": ["rich", "savory", "buttery"],
                "texture": "crisp crust, tender center",
                "temperature": "warm",
                "occasion": "special dinner",
                "energy_required": "high",
                "meal_type": "main",
                "diet_tags": [],
                "budget": "high",
                "prep_minutes": 45,
                "cook_minutes": 35,
                "total_minutes": 80,
                "nutrition_score": 7.8,
                "ingredients_needed": ["beef tenderloin", "mushrooms", "puff pastry", "mustard", "prosciutto", "egg yolk"],
                "missing_ingredients": ["thyme", "shallots"],
                "instructions": [
                    "Step 1: Season and sear the beef on all sides so a browned crust forms, then let it cool completely before wrapping.",
                    "Step 2: Cook the mushrooms, shallots, and thyme down until the mixture is dry; this keeps the pastry from getting soggy.",
                    "Step 3: Wrap the beef with mustard, prosciutto, and the mushroom filling, then chill it briefly so the shape holds.",
                    "Step 4: Enclose the wrapped beef in puff pastry, seal the edges tightly, and brush the top with egg wash.",
                    "Step 5: Bake until the pastry is deeply golden and the center reaches your target doneness, then rest before slicing.",
                ],
                "nutrition_per_serving": {"calories": 680, "protein": "42g", "carbs": "28g", "fat": "40g"},
                "tips": "The cooling and resting steps matter as much as the baking time for a clean slice.",
            },
            {
                "name": "Hyderabadi Dum Biryani",
                "cuisine": "Indian",
                "difficulty": "Expert",
                "difficulty_level": 5,
                "prep_time": "60 minutes",
                "cook_time": "50 minutes",
                "servings": 6,
                "comfort_score": 8,
                "learning_value": 10,
                "techniques": ["marination", "layering", "dum cooking", "rice parboiling"],
                "estimated_cleanup": "high",
                "skill_tags": ["rice", "spice", "layering"],
                "emotion_tags": ["celebratory", "adventurous", "nostalgic"],
                "taste_profile": ["fragrant", "spiced", "rich"],
                "texture": "fluffy rice, tender meat",
                "temperature": "warm",
                "occasion": "celebration feast",
                "energy_required": "high",
                "meal_type": "main",
                "diet_tags": [],
                "budget": "medium",
                "prep_minutes": 60,
                "cook_minutes": 50,
                "total_minutes": 110,
                "nutrition_score": 7.2,
                "ingredients_needed": ["basmati rice", "chicken or lamb", "yogurt", "fried onions", "spices", "mint", "saffron"],
                "missing_ingredients": ["ghee", "lemon"],
                "instructions": [
                    "Step 1: Marinate the meat with yogurt, spices, ginger garlic, and fried onions so the flavor penetrates deeply.",
                    "Step 2: Parboil the rice until it is about 70 percent cooked, then drain it well so the grains stay separate.",
                    "Step 3: Build the biryani in layers by alternating meat, rice, mint, saffron milk, and fried onions.",
                    "Step 4: Seal the pot and cook on very low heat so the steam finishes the rice and meat together.",
                    "Step 5: Rest the pot before serving, then fluff the layers gently so the grains stay long and fragrant.",
                ],
                "nutrition_per_serving": {"calories": 620, "protein": "31g", "carbs": "66g", "fat": "24g"},
                "tips": "Low heat and a tight seal are the main skills that make dum biryani work.",
            },
            {
                "name": "Croissants",
                "cuisine": "French",
                "difficulty": "Expert",
                "difficulty_level": 5,
                "prep_time": "180 minutes",
                "cook_time": "20 minutes",
                "servings": 8,
                "comfort_score": 6,
                "learning_value": 10,
                "techniques": ["lamination", "proofing", "folding", "baking"],
                "estimated_cleanup": "high",
                "skill_tags": ["pastry", "precision", "butter control"],
                "emotion_tags": ["curious", "focused", "celebratory"],
                "taste_profile": ["buttery", "flaky", "light"],
                "texture": "flaky layers",
                "temperature": "warm",
                "occasion": "bakery project",
                "energy_required": "high",
                "meal_type": "breakfast",
                "diet_tags": ["vegetarian"],
                "budget": "medium",
                "prep_minutes": 180,
                "cook_minutes": 20,
                "total_minutes": 200,
                "nutrition_score": 5.8,
                "ingredients_needed": ["flour", "butter", "milk", "yeast", "sugar", "salt"],
                "missing_ingredients": ["egg wash"],
                "instructions": [
                    "Step 1: Mix and knead the dough just until smooth, then chill it so the butter can stay cold during laminating.",
                    "Step 2: Enclose the butter block in the dough and roll it out carefully, keeping the rectangle even so the layers stay tidy.",
                    "Step 3: Fold the dough several times with resting periods in between to build thin layers without melting the butter.",
                    "Step 4: Shape the triangles into croissants, proof them until puffy, and avoid overproofing so the layers still hold.",
                    "Step 5: Brush with egg wash and bake until deeply golden and crisp, then cool on a rack so the steam does not soften the crust.",
                ],
                "nutrition_per_serving": {"calories": 260, "protein": "6g", "carbs": "28g", "fat": "14g"},
                "tips": "Keeping the butter cold is the main technical skill here.",
            },
            {
                "name": "Fresh Handmade Ravioli",
                "cuisine": "Italian",
                "difficulty": "Hard",
                "difficulty_level": 4,
                "prep_time": "90 minutes",
                "cook_time": "10 minutes",
                "servings": 4,
                "comfort_score": 8,
                "learning_value": 9,
                "techniques": ["pasta dough", "rolling", "filling", "sealing"],
                "estimated_cleanup": "medium",
                "skill_tags": ["pasta", "precision", "hands-on"],
                "emotion_tags": ["focused", "curious", "nostalgic"],
                "taste_profile": ["savory", "tender", "rich"],
                "texture": "silky pasta",
                "temperature": "warm",
                "occasion": "weekend project",
                "energy_required": "high",
                "meal_type": "main",
                "diet_tags": ["vegetarian"],
                "budget": "medium",
                "prep_minutes": 90,
                "cook_minutes": 10,
                "total_minutes": 100,
                "nutrition_score": 7.0,
                "ingredients_needed": ["flour", "egg", "ricotta", "spinach", "parmesan", "nutmeg"],
                "missing_ingredients": ["olive oil", "garlic"],
                "instructions": [
                    "Step 1: Mix the pasta dough until smooth, then let it rest so the gluten relaxes and the dough rolls more easily.",
                    "Step 2: Make the filling and keep it thick so it does not leak while you shape the ravioli.",
                    "Step 3: Roll the dough thinly and cut it into even squares or circles.",
                    "Step 4: Place small mounds of filling on one sheet, cover with another sheet, and press out the air before sealing the edges.",
                    "Step 5: Boil the ravioli for a few minutes until they float, then toss them with butter or sauce and serve immediately.",
                ],
                "nutrition_per_serving": {"calories": 470, "protein": "20g", "carbs": "54g", "fat": "18g"},
                "tips": "Rolling the dough evenly makes the sealing process much easier.",
            },
            {
                "name": "Tonkotsu Ramen",
                "cuisine": "Japanese",
                "difficulty": "Hard",
                "difficulty_level": 4,
                "prep_time": "120 minutes",
                "cook_time": "180 minutes",
                "servings": 4,
                "comfort_score": 9,
                "learning_value": 9,
                "techniques": ["broth building", "fat emulsification", "noodle timing", "topping prep"],
                "estimated_cleanup": "high",
                "skill_tags": ["broth", "umami", "timing"],
                "emotion_tags": ["cozy", "tired", "lonely", "curious"],
                "taste_profile": ["rich", "savory", "deep umami"],
                "texture": "creamy broth",
                "temperature": "warm",
                "occasion": "slow weekend meal",
                "energy_required": "high",
                "meal_type": "soup",
                "diet_tags": [],
                "budget": "medium",
                "prep_minutes": 120,
                "cook_minutes": 180,
                "total_minutes": 300,
                "nutrition_score": 7.5,
                "ingredients_needed": ["pork bones", "ramen noodles", "garlic", "ginger", "scallions", "soy sauce", "eggs"],
                "missing_ingredients": ["nori", "sesame oil"],
                "instructions": [
                    "Step 1: Simmer the bones for a long time and skim the surface as needed so the broth turns clean and rich instead of cloudy and bitter.",
                    "Step 2: Add aromatics and keep the broth at a steady low simmer so the fat emulsifies slowly and gives the soup body.",
                    "Step 3: Prepare the toppings while the broth cooks, because ramen depends on timing and organized prep.",
                    "Step 4: Cook the noodles separately at the very end so they stay springy and do not over-soften in the bowl.",
                    "Step 5: Build each bowl with broth, noodles, egg, and toppings, then serve immediately while the surface is still steaming hot.",
                ],
                "nutrition_per_serving": {"calories": 720, "protein": "32g", "carbs": "68g", "fat": "34g"},
                "tips": "The broth is the skill test here; patience matters more than speed.",
            },
            {
                "name": "Macarons",
                "cuisine": "French",
                "difficulty": "Expert",
                "difficulty_level": 5,
                "prep_time": "90 minutes",
                "cook_time": "20 minutes",
                "servings": 18,
                "comfort_score": 6,
                "learning_value": 10,
                "techniques": ["meringue", "macaronage", "piping", "resting"],
                "estimated_cleanup": "medium",
                "skill_tags": ["precision", "patience", "pastry"],
                "emotion_tags": ["curious", "focused", "celebratory"],
                "taste_profile": ["sweet", "delicate", "airy"],
                "texture": "crisp shell, chewy center",
                "temperature": "room temperature",
                "occasion": "patissier project",
                "energy_required": "high",
                "meal_type": "dessert",
                "diet_tags": ["vegetarian", "gluten-free"],
                "budget": "medium",
                "prep_minutes": 90,
                "cook_minutes": 20,
                "total_minutes": 110,
                "nutrition_score": 5.5,
                "ingredients_needed": ["almond flour", "powdered sugar", "egg whites", "granulated sugar", "food coloring"],
                "missing_ingredients": ["buttercream or ganache filling"],
                "instructions": [
                    "Step 1: Sift the dry ingredients carefully so the shells stay smooth and the batter does not have lumps.",
                    "Step 2: Whip the egg whites to a stable meringue, then add sugar gradually so the foam stays glossy and firm.",
                    "Step 3: Fold the dry ingredients into the meringue until the batter flows slowly from the spatula, which is the key texture test.",
                    "Step 4: Pipe evenly sized circles and let them rest until a skin forms on the surface before baking.",
                    "Step 5: Bake with controlled heat, cool completely, and fill only after the shells are fully set.",
                ],
                "nutrition_per_serving": {"calories": 90, "protein": "2g", "carbs": "12g", "fat": "4g"},
                "tips": "Macarons are all about batter texture, resting time, and even sizing.",
            },
            {
                "name": "Fresh Sushi Rolls",
                "cuisine": "Japanese",
                "difficulty": "Hard",
                "difficulty_level": 4,
                "prep_time": "75 minutes",
                "cook_time": "15 minutes",
                "servings": 4,
                "comfort_score": 7,
                "learning_value": 8,
                "techniques": ["rice seasoning", "rolling", "knife work", "assembly"],
                "estimated_cleanup": "medium",
                "skill_tags": ["knife control", "precision", "assembly"],
                "emotion_tags": ["focused", "curious", "adventurous"],
                "taste_profile": ["fresh", "light", "savory"],
                "texture": "clean, crisp",
                "temperature": "cool",
                "occasion": "skill-building meal",
                "energy_required": "medium",
                "meal_type": "main",
                "diet_tags": ["pescatarian"],
                "budget": "medium",
                "prep_minutes": 75,
                "cook_minutes": 15,
                "total_minutes": 90,
                "nutrition_score": 8.0,
                "ingredients_needed": ["sushi rice", "nori", "fish or vegetables", "rice vinegar", "cucumber", "avocado"],
                "missing_ingredients": ["sesame seeds", "wasabi"],
                "instructions": [
                    "Step 1: Cook and season the rice so it becomes sticky, glossy, and easy to shape without turning mushy.",
                    "Step 2: Prepare the fillings by cutting them into long, even strips so the rolls stay neat.",
                    "Step 3: Lay out the nori, spread a thin layer of rice, and leave a small border at the top edge.",
                    "Step 4: Add the fillings, roll tightly with steady pressure, and seal the edge so the roll holds together.",
                    "Step 5: Slice with a sharp damp knife and serve immediately so the nori stays crisp and the rice stays cleanly cut.",
                ],
                "nutrition_per_serving": {"calories": 360, "protein": "18g", "carbs": "48g", "fat": "10g"},
                "tips": "Wet the knife between cuts for cleaner slices.",
            },
        ]

        return [Recipe.from_dict(item) for item in catalog_data]

    @staticmethod
    def _tokens(items: list[str]) -> set[str]:
        tokens: set[str] = set()
        for item in items:
            for token in re.findall(r"[a-z]+", item.lower()):
                tokens.add(token)
        return tokens
